version: '2'
services:
  mycat-docker:
    image: registry.alauda.cn/longhronshen/mycat-docker
    restart: always
    volumes:
    - ./mycat/conf/:/usr/local/mycat/conf/
    ports:
    - "8066:8066"
    - "9066:9066"
  mycat-ef:
    image: registry.alauda.cn/longhronshen/mycat-ef
    restart: always
    volumes:
    - ./mycat/:/usr/local/mycat/
    ports:
    - "7066:7066"
